- name: check for centos 7
  fail:
    msg: >-
        Docker CE requires CentOS 7. Please use the `centos6` branch of this role
        to deploy on CentOS 6.
  when: ansible_distribution_major_version != "7"

# Remove Docker Engine if `docker_engine_cleanup` is set
- include: cleanup.yml
  when: docker_engine_cleanup|default(false)|bool

- name: add docker main repository
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: create systemd override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: ansible_distribution_major_version == "7"

- name: add systemd override
  copy:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: install docker
  yum:
    name: docker-ce
    state: present
  register: docker_install

- name: create sysconfig file
  template:
    src: sysconfig.j2
    dest: /etc/sysconfig/docker

- name: start and enable docker
  service:
    name: docker
    state: started
    enabled: yes
